name: GITHUB ACTIONS TP PARTIE 2
run-name: ${{ github.actor }} GITHUB ACTIONS TP PARTIE 2
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22"
      - name: Set github user
        run: git config user.email "test@example.com" && git config user.name "CI/CD - MMI"
